import{S as p,A as y}from"./assets/vendor-52a7ade3.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const u={openMenuBtn:document.querySelector("[data-menu-open]"),closeMenuBtn:document.querySelector("[data-menu-close]"),menu:document.querySelector("[data-menu]")};u.openMenuBtn.addEventListener("click",f);u.closeMenuBtn.addEventListener("click",f);function f(){u.menu.classList.toggle("is-open")}document.getElementById("dropdownBtn").addEventListener("click",function(){var e=document.getElementById("dropdownContent");e.style.display==="block"?e.style.display="none":e.style.display="block"});const s=document.body,i=document.getElementById("myModal"),a=document.querySelector(".footer_form");document.addEventListener("DOMContentLoaded",function(){a.addEventListener("submit",function(n){n.preventDefault(),i.style.display="block",m(),a.reset()}),i.querySelector(".close").addEventListener("click",function(){i.style.display="none",d()}),window.addEventListener("click",function(n){n.target===i&&(i.style.display="none",d())}),window.addEventListener("keydown",function(n){n.key==="Escape"&&(i.style.display="none",d())})});function m(){s.style.height="100vh",s.style.overflowY="hidden",s.style.paddingRight="15px",i.style.height="100vh",i.style.overflowY="hidden"}function d(){s.style.height="auto",s.style.overflowY="auto",s.style.paddingRight="none",i.style.height="auto",i.style.overflowY="auto"}const v="https://portfolio-js.b.goit.study/api",w={get:"reviews",post:"requests"};function h(){return fetch(`${v}/${w.get}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}new p(".swiper",{direction:"vertical",loop:!0,slidesPerView:1,slidesPerGroup:1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});const g=document.querySelector(".menu-reviews-list-ul");h().then(e=>{console.log(e),g.insertAdjacentHTML("beforeend",L(e))}).catch(e=>{console.log(e)});function L(e){return e.map(({_id:n,author:r,avatar_url:l,review:t})=>`<li class="menu-reviews-item-li menu-item swiper-slide-reviews" id="${n}">
         <img
           class="icon-reviews-img"
           src="${l}"
           width="48"
           height="48"
           alt="${r}'s avatar"
         />
         <div class="container-reviews-title-text">
           <h3 class="reviews-title-h3">${r}</h3>
           <p class="reviews-text">${t}</p>
         </div>
      </li>`).join("")}new y(".accordion-container",{duration:400,showMultiple:!0,onOpen:function(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
