import{S as y,N as p,A as m}from"./assets/vendor-793b568a.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();const r={openMenuBtn:document.querySelector("[data-menu-open]"),closeMenuBtn:document.querySelector("[data-menu-close]"),menu:document.querySelector("[data-menu]"),body:document.querySelector("body")};r.openMenuBtn.addEventListener("click",f);r.closeMenuBtn.addEventListener("click",f);function f(){r.menu.classList.toggle("is-open"),r.menu.classList.contains("is-open")&&(r.body.style.overflow="hidden")}document.getElementById("dropdownBtn").addEventListener("click",function(){var t=document.getElementById("dropdownContent");t.style.display==="block"?t.style.display="none":t.style.display="block"});const s=document.body,i=document.getElementById("myModal"),u=document.querySelector(".footer_form"),w=document.querySelector(".btm-submit");w.addEventListener("click",function(){u.addEventListener("submit",function(n){n.preventDefault(),i.style.display="block",h(),u.reset()}),i.querySelector(".close").addEventListener("click",function(){i.style.display="none",a()}),window.addEventListener("click",function(n){n.target===i&&(i.style.display="none",a())}),window.addEventListener("keydown",function(n){n.key==="Escape"&&(i.style.display="none",a())})});function h(){s.style.height="100vh",s.style.overflowY="hidden",s.style.paddingRight="15px",i.style.height="100vh",i.style.overflowY="hidden"}function a(){s.style.height="auto",s.style.overflowY="auto",s.style.paddingRight="none",i.style.height="auto",i.style.overflowY="auto"}const v="https://portfolio-js.b.goit.study/api",g={get:"reviews",post:"requests"};async function b(){return await fetch(`${v}/${g.get}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const L=document.querySelector(".menu-reviews-list-ul");b().then(t=>{L.insertAdjacentHTML("beforeend",E(t)),new y(".swiper-reviews-wrap",{direction:"horizontal",modules:[p],slidesPerView:2,spaceBetween:30,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}})}).catch(t=>{console.log("error",t)});function E(t){return t.map(({_id:n,author:c,avatar_url:l,review:e})=>`<li class="menu-reviews-item-li menu-item swiper-slide" id="${n}">  
         <img 
           class="icon-reviews-img" 
           src="${l}" 
           width="48" 
           height="48" 
           alt="${c}'s avatar" 
         /> 
         <div class="container-reviews-title-text"> 
           <h3 class="reviews-title-h3">${c}</h3> 
           <p class="reviews-text">${e}</p> 
         </div> 
      </li>`).join("")}const S=document.querySelector(".accordion-container");new m(S,{});new y(".swiper-container",{direction:"horizontal",slidesPerView:1,slidesPerGroup:1,spaceBetween:10,loop:!1,autoHeight:!0});
//# sourceMappingURL=commonHelpers.js.map
